### PR TITLE
add eslint config to repo to integrate with text editors

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by origamiserviceuser** [comment]
o-labels bundle size difference from 5.0.2 to 66a8634e259e0ad82e7ffecebbede1bbbd08fa97
No bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-labels bundle size difference from 5.0.2 to 7c63a668b350bcc3f733489cd0546a14ec54527c
No bundle size differences found.

**Comment by origamiserviceuser** [comment]
o-labels bundle size difference from 5.0.2 to fc28ff7d2221b64d7e06854900050c82c662171a
No bundle size differences found.

**Review by notlee — APPROVED** [review]

**Comment by origamiserviceuser** [comment]
o-labels bundle size difference from 5.0.2 to a02e1b9e8e3fa6abb5e4b8b098c6957a6eb3bdd0
No bundle size differences found.

**Pull request merged**
